import express from 'express';
import pool from '../db.js';
import authMiddleware from '../middleware/authMiddleware.js';

const router = express.Router();

// Create user profile (called after signup)
router.post('/', authMiddleware, async (req, res) => {
    try {
        const user_id = req.user_id;
        const { full_name, age, sex } = req.body;

        // Validate required fields
        if (!full_name || !age || !sex) {
            return res.status(400).json({
                error: "Missing required fields: full_name, age, sex"
            });
        }

        // Validate age
        if (typeof age !== 'number' || age < 0 || age > 150) {
            return res.status(400).json({
                error: "Age must be a number between 0 and 150"
            });
        }

        // Check if profile already exists
        const existingProfile = await pool.query(
            "SELECT id FROM user_profiles WHERE user_id = $1",
            [user_id]
        );

        if (existingProfile.rows.length > 0) {
            return res.status(400).json({
                error: "User profile already exists. Use PUT to update."
            });
        }

        // Create profile (timestamp auto-generated by database)
        const result = await pool.query(
            `INSERT INTO user_profiles (user_id, full_name, age, sex, created_at)
       VALUES ($1, $2, $3, $4, NOW())
       RETURNING id, user_id, full_name, age, sex, created_at`,
            [user_id, full_name, age, sex]
        );

        // Also create default baseline for new user
        try {
            await pool.query(
                `INSERT INTO user_baselines 
         (user_id, avg_sleep_hours, avg_activity_score, med_adherence_pct, 
          typical_sleep_window, avg_sleep_midpoint_min, avg_sleep_duration_min, 
          avg_activity_MET, avg_activity_duration_min)
         VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)`,
                [user_id, 7.5, 50, 80, "22:00-06:00", 1380, 480, 1.2, 30]
            );
        } catch (err) {
            // If baseline creation fails, it's not critical for profile creation
            console.warn("Warning: Could not create default baseline:", err.message);
        }

        res.status(201).json({
            message: "Profile created successfully",
            profile: result.rows[0]
        });

    } catch (err) {
        console.error("CREATE PROFILE ERROR:", err);
        res.status(500).json({
            error: "Failed to create profile",
            message: err.message
        });
    }
});

// Get user profile
router.get('/', authMiddleware, async (req, res) => {
    try {
        const user_id = req.user_id;

        const result = await pool.query(
            `SELECT id, user_id, full_name, age, sex, created_at
       FROM user_profiles
       WHERE user_id = $1`,
            [user_id]
        );

        if (result.rows.length === 0) {
            return res.status(404).json({
                error: "Profile not found. Please complete profile setup.",
                requires_profile_setup: true
            });
        }

        res.json({
            profile: result.rows[0]
        });

    } catch (err) {
        console.error("GET PROFILE ERROR:", err);
        res.status(500).json({
            error: "Failed to fetch profile",
            message: err.message
        });
    }
});

// Update user profile
router.put('/', authMiddleware, async (req, res) => {
    try {
        const user_id = req.user_id;
        const { full_name, age, sex } = req.body;

        // Validate required fields
        if (!full_name || age === undefined || !sex) {
            return res.status(400).json({
                error: "Missing required fields: full_name, age, sex"
            });
        }

        // Validate age
        if (typeof age !== 'number' || age < 0 || age > 150) {
            return res.status(400).json({
                error: "Age must be a number between 0 and 150"
            });
        }

        // Update profile (note: do NOT update created_at on update)
        const result = await pool.query(
            `UPDATE user_profiles
       SET full_name = $1, age = $2, sex = $3
       WHERE user_id = $4
       RETURNING id, user_id, full_name, age, sex, created_at`,
            [full_name, age, sex, user_id]
        );

        if (result.rows.length === 0) {
            return res.status(404).json({
                error: "Profile not found"
            });
        }

        res.json({
            message: "Profile updated successfully",
            profile: result.rows[0]
        });

    } catch (err) {
        console.error("UPDATE PROFILE ERROR:", err);
        res.status(500).json({
            error: "Failed to update profile",
            message: err.message
        });
    }
});

export default router;
